### ISSUE TITLE
springcloud

### ISSUE THREAD

**Issue by mengweilong** [mengweilong/mengweilong.github.io#37]
```
server:
  port: 8888
eureka:
  instance:
    hostname: eureka
    lease-expiration-duration-in-seconds: 90    //服务过期时间
    lease-renewal-interval-in-seconds: 30    //续约间隔
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
    registry-fetch-interval-seconds: 30    //定时拉取服务列表
  server:
    enable-self-preservation: false    //自我保护开关
spring:
  application:
    name: eureka-server
```
